language: node_js
node_js:
- '6'
- '8'
- '10'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env: CXX=g++-4.8 NODE_ENV=test
deploy:
  provider: npm
  email: mahnunchik@gmail.com
  api_key:
    secure: KEJHeC7dEuxQreiFaDu9wIK2c/Sa19w5y4okfE1FyOoLDFBOsfsPDH9CRTacw2miJFmyjTAT5pvuACZS2mHwwopsd4B+vk5KmauUFgoz86AeY8EIbG+yP+uRiSdFJbA9B0Y2oeNOGqDqYs+rZ+XvMythOJS7eG0gfFKLv26sDfY=
  on:
    tags: true
    repo: mahnunchik/gulp-responsive
    node: '6'
